language: java
before_install:
- openssl aes-256-cbc -K $encrypted_12a8d6dae678_key -iv $encrypted_12a8d6dae678_iv
  -in settings.xml.enc -out settings.xml -d
- openssl aes-256-cbc -K $encrypted_9a895d496368_key -iv $encrypted_9a895d496368_iv
  -in settings.xml.enc -out ~/.m2/settings.xml -d
after_success:
- mvn deploy
